uploads = []

[[generated]]
id = "S8a7ApylVFJoJ_46GRn33"
uri = "file://artifacts/agro-calc/assets/images/icon.png"
type = "image"
title = "agro-calc-icon"

[[outputs]]
id = "WGDhpcodSc9rqsssjuY5U"
uri = "file://AgroCalc_KLM_Инструкция.docx"
type = "word_document"
title = "AgroCalc КЛМ — Руководство пользователя.docx"
